### ISSUE TITLE
Sum instead of mean?

### ISSUE THREAD

**Issue by jaseeverett** [PlanktonTeam/planktonr#17]
https://github.com/PlanktonTeam/planktonr/blob/ceee8f011df097127e8b1186f3be6449e4d4c702/R/pr_get_chemistry.R#L34-L43

DIC seems to be summed, and not averaged here. Is this intentional @clairedavies?

**Comment by clairedavies** [comment]
mean

**Comment by jaseeverett** [comment]
Updated
