### ISSUE TITLE
`pr_match_Altimetry` crashes when data not found

### ISSUE THREAD

**Issue by jaseeverett** [PlanktonTeam/planktonr#170]
When running the example for `pr_match_Altimetry` using 100 observations, it crashes. I suspect it is related to one of the date/lat/lon combinations not being found. When I run the code using only 10 obs, it works correctly.
```
df <- head(pr_get_DataLocs("NRS"), 10)
res_spat <- 10
altout <- pr_match_Altimetry(df, pr = "GSLA")
```

The error is:
```
oc_open: server error retrieving url: code=400 message="Unrecognized request"oc_open: server error retrieving url: code=400 message="Unrecognized request"
 Error in UseMethod("xml_find_all") : 
no applicable method for 'xml_find_all' applied to an object of class "NULL"
```

**Comment by jaseeverett** [comment]
The crash has been fixed however there are 3 additional things which should be addressed

- [ ] The sorted order of the data is changed. The returned data frame is sorted by date, rather than kept in the original order. It should always come back in the same order as the user provides.
- [ ] A minor one but the lat/lon columns in the returned data frame are reversed. Again, they should come back in the same order as they were send out.
- [ ] The returned data frame has missing rows (presumably if there is no data). 
```
df <- head(pr_get_DataLocs("NRS"), 100)
res_spat <- 10
altout <- pr_match_Altimetry(df, pr = "GSLA")
```
returns `altout` as only 83 rows, instead of 100. If the data missing from the satellite data, it should return an NA rather than removing that row all together.

**Comment by jaseeverett** [comment]
I'm happy to work on these issues if you prefer @clairedavies

**Comment by jaseeverett** [comment]
Also noted that the examples now fail, even using head(df, 5) because the first 5 are prior to 2019. Need to add a catch for when no data is prior to 2019

**Comment by clairedavies** [comment]
Done - caused because no data was returned, now all records are returned with NaN where necessary, trycatch and  if statement combination used to prevent error message appearing in trycatch function even though the function was actually working.
