### ISSUE TITLE
Replace for loops with purrr::map

### ISSUE THREAD

**Issue by clairedavies** [PlanktonTeam/planktonr#31]
This is the obvious example but we should use purrr where possible, it is more efficient. I suspect that it will also be an expectation if we want to publish the package through CRAN. I've been using it a fair bit since I originally wrote this code.

**Comment by jaseeverett** [comment]
Agreed. I've wanted to learn purrr better as well so this is worth doing. Will consider this as we go.

**Comment by clairedavies** [comment]
There's a good chapter in Adv R, gives you a good idea about what it can do - its way clever

**Comment by jaseeverett** [comment]
Claire has been purrring happily
