### ISSUE TITLE
tidy up grepl 

### ISSUE THREAD

**Issue by clairedavies** [PlanktonTeam/planktonr#32]
In lots of places I have used code like !grepl("cf.", .data$Species) & !grepl("/", .data$Species)) 

This can be neatened by defining some consistent patterns we use (so we only have to update this once) and using in grepl function

patterns <- c("cf.", "spp.", "/", "type")
!grepl(paste(patterns, collapse="|"), Species)

**Comment by jaseeverett** [comment]
Just confirming that you want to remove any rows that contain the `patterns` and not simply remove the pattern but keep what is left?
