### ISSUE TITLE
update to code for all species products

### ISSUE THREAD

**Issue by clairedavies** [PlanktonTeam/planktonr#33]
In an update of the change log tables I changed the content of the taxon_name table. The old version was genus || species, but this could have caused duplicates in the event that we learn to speciate some of the copepod males we don't do now. This means that the taxon name in the change log table is now the same as the data table and the implication of this change is that the filter operation needs to come before the mutate operation in the species product functions. This occurs twice in each function for change log and non change log operations. 

NRS_Phyto_BioVSpeciesMat
NRS_Phyto_SpeciesMat
NRS_Zoop_CopesMat
NRS_Zoop_CopesMat
CPR_Phyto_BioVSpeciesMat
CPR_Phyto_SpeciesMat
CPR_Zoop_CopesMat
CPR_Zoop_CopesMat

Example of code section to be changed
NRSSpecP1 <- NRSPdat %>%
    mutate(TaxonName = paste0(.data$Genus, ' ', .data$Species)) %>% # remove .data$Comments about with flagellates or cilliates etc.
    filter(!.data$TaxonName %in% levels(as.factor(nrsls$TaxonName))
           & .data$Species != "spp." & !is.na(.data$Species) & !grepl("cf.", .data$Species) & !grepl("/", .data$Species)) %>%
    group_by(.data$TripCode, .data$TaxonName) %>%
    summarise(Cells_L = sum(.data$Cells_L, na.rm = TRUE), .groups = "drop")

**Comment by jaseeverett** [comment]
All this code is now done by the AODN. Closing.
